name: Gradle Publish Release

on:
  workflow_call:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Set up Java
        uses: actions/setup-java@v5
        with:
          distribution: "temurin"
          java-version: "25"
          cache: "gradle"

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v5

      - name: Configure GitHub Packages credentials
        run: |
          mkdir -p ~/.gradle
          {
            echo "github.user=${{ github.actor }}"
            echo "github.token=${{ secrets.GITHUB_TOKEN }}"
          } > ~/.gradle/gradle.properties

      - name: Build
        run: ./gradlew build -Pversion=${{ github.ref_name }}

      - name: Publish package
        run: |
          tag_name="${GITHUB_REF#refs/tags/}"
          # Remove the leading 'v' from the tag to get the version number
          version_override="${tag_name#v}"

          ./gradlew publish -PversionOverride="$version_override"